-- Generated by scripts/gen-schema-manifest.js — safe to run more than once.
--
-- Brings an older database up to date with supabase/schema.sql: every column the
-- app writes is added if missing. This is the fix for the recurring
-- "Could not find the '<column>' column of '<table>' in the schema cache" errors,
-- which silently drop fields on insert (see lib/resilientInsert.ts).

alter table project_members
  add column if not exists added_at timestamptz not null default now(),
  add column if not exists project_id uuid references projects(id) on delete cascade,
  add column if not exists role text not null default 'member',
  add column if not exists user_id uuid references users(id) on delete cascade;

alter table project_statuses
  add column if not exists color text not null default '#9AA1AC',
  add column if not exists is_done boolean not null default false,
  add column if not exists key text,
  add column if not exists name text,
  add column if not exists project_id uuid references projects(id) on delete cascade,
  add column if not exists sort_order integer not null default 0;

alter table projects
  add column if not exists accent_color text not null default '#12A594',
  add column if not exists archived_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists created_by uuid references users(id) on delete set null,
  add column if not exists default_view text not null default 'kanban',
  add column if not exists description text not null default '',
  add column if not exists end_date date,
  add column if not exists icon text not null default 'folder',
  add column if not exists name text,
  add column if not exists owner_id uuid references users(id) on delete set null,
  add column if not exists percent_complete integer check (percent_complete is null or percent_complete between 0 and 100),
  add column if not exists start_date date,
  add column if not exists status text not null default 'active',
  add column if not exists updated_at timestamptz not null default now();

alter table task_activity
  add column if not exists action text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists details text,
  add column if not exists task_id uuid references tasks(id) on delete cascade,
  add column if not exists user_id uuid references users(id) on delete cascade;

alter table task_comments
  add column if not exists content text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists task_id uuid references tasks(id) on delete cascade,
  add column if not exists user_id uuid references users(id) on delete cascade;

alter table tasks
  add column if not exists assignee_id uuid references users(id) on delete set null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists created_by uuid references users(id) on delete set null,
  add column if not exists description text not null default '',
  add column if not exists due_date date,
  add column if not exists duration_days integer check (duration_days is null or duration_days >= 0),
  add column if not exists parent_task_id uuid references tasks(id) on delete cascade,
  add column if not exists percent_complete integer not null default 0 check (percent_complete between 0 and 100),
  add column if not exists priority text not null default 'medium',
  add column if not exists project_id uuid references projects(id) on delete cascade,
  add column if not exists sort_order integer not null default 0,
  add column if not exists start_date date,
  add column if not exists status text not null default 'todo',
  add column if not exists tags text[] default array[]::text[],
  add column if not exists title text,
  add column if not exists updated_at timestamptz not null default now();

alter table users
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists is_placeholder boolean not null default false,
  add column if not exists name text not null default '',
  add column if not exists password_hash text,
  add column if not exists role text not null default 'member',
  add column if not exists title text not null default '',
  add column if not exists username text unique check (char_length(username) between 3 and 32);

-- Make PostgREST pick up every new column immediately, otherwise the schema
-- cache keeps serving the old shape and the API keeps 400ing.
notify pgrst, 'reload schema';
